### ISSUE TITLE
Fix translation

### ISSUE THREAD

**Issue by LorranSutter** [bernard-rodrigues/lantern-legend#1]
Replace `Voltar` with an equivalent English word in:

https://github.com/bernard-rodrigues/lantern-legend/blob/4acfd87f50fa1c448be1d44a24579241c1371020/src/pages/Credits.tsx#L33

https://github.com/bernard-rodrigues/lantern-legend/blob/4acfd87f50fa1c448be1d44a24579241c1371020/src/pages/Scoreboard.tsx#L51

**Comment by bernard-rodrigues** [comment]
Thanks for your support. Issue fixed, as recommended.
